### PR TITLE
Expose the line content

### PR DESCRIPTION
**Pull request by masom**
Lines can be iterated but their content is private.

### CODE REVIEW

**Comment by sanemat** [comment]
Hi, thank you for your request!
But I don't have a use case about this API. Do you need any help?

For debugging?

**Comment by masom** [comment]
Making the content property public would allow displaying / using the content value when iterating over the lines of a diff, similar to the GitHub files changed tab.

**Comment by freemanoid** [comment]
Hey @sanemat do you need any other reason except that @masom mentioned to merge this? I also want to use this gem for reading diffs and diff content is a key.

**Comment by sanemat** [comment]
I change my opinion! I accept this pull request. I understand this use case.

**Comment by sanemat** [comment]
Hi, @masom @freemanoid  I ship `v2.3.0`! :cactus:

**Pull request merged**
